name: Dev Workflow
  

on: 
  push:
  workflow_dispatch:
  
jobs:
  start:
    name: testing
    runs-on: ubuntu-latest
    steps:
      - name: change
        run: |
          curl ifconfig.me/ip
          
      # - name: runch dockerhub
      #   run: |
      #     python dg-hub.py -u Guerroudj-a  -d
