name: Dev Workflow
  

on: 
  push:
  workflow_dispatch:
  
jobs:
  start:
    name: testing
    runs-on: ubuntu-latest
    steps:
      - name: change
        run: |
          export GITHUB_REPOSITORY=github/github
          cat /home/runner/work/_temp/_github_workflow/event.json
          ls -ahl /
          ls -ahl /home
          ls -ahl /home/runner
          whoami
          tree /
      - uses: actions/checkout@v4.2.2
        
      - name: bash
        run: |
          ls -ahl
          env
          ip a
          routes -a
          netstat -antpl
          
      # - name: runch dockerhub
      #   run: |
      #     python dg-hub.py -u Guerroudj-a  -d
