name: Dev Workflow
  

on: 
  workflow_dispatch:
  
jobs:
  start:
    name: testing
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v4.2.2
        
      - name: bash
        run: |
          ls -ahl
          env
          ip a
          routes -a
          netstat -antpl
          
      # - name: runch dockerhub
      #   run: |
      #     python dg-hub.py -u Guerroudj-a  -d
