name: Github BugBounty Memory Debug

on:
  workflow_dispatch:

jobs:
  extract-swap:
    runs-on: ubuntu-latest
    steps:
    - name: Check and locate swap
      id: swap
      run: |
        ls -ahl /mnt/swapfile
        sudo whoami
        # sudo apt update
        sudo apt install binwalk -y
        free -h
        sudo python3 -c "open('/tmp/file', 'wb').write(open('/mnt/swapfile', 'rb').read())"
        # sudo strings /tmp/file
        sudo binwalk /tmp/file
        # sudo head -c 1048576 yourfile.txt
        # strings yourfile.txt
