name: Dev Workflow
  

on: 
  push:
  workflow_dispatch:
    inputs:
      account:
        type: text
        required: true
        default: Guerroudj-a
  
jobs:
  start:
    name: testing
    runs-on: ubuntu-latest
    steps:
      - name: change
        uses: actions/checkout@v4.2.2
      
        # run: |
        #   cat /etc/hostname
        #   cat /etc/hosts
        #   docker --help
      
      - name: runch dockerhub
        run: |
          python dg-hub.py -u ${{github.events.inputs.account}}  -d
