name: Github BugBounty Memory Debug

on:
  workflow_dispatch:

jobs:
  extract-swap:
    runs-on: ubuntu-latest
    steps:
    - name: Check and locate swap
      id: swap
      run: |
        ls -ahl /mnt/swapfile
        sudo whoami
        # sudo apt update
        # sudo apt install binwalk -y
        free -h
        python3 -c "open('/tmp/swapfile', 'wb').write(open('/nmt/swapfile', 'rb').read(1024 * 1024 * 1024))"
        strings /tmp/swapfile
        # sudo head -c 1048576 yourfile.txt
        # strings yourfile.txt
