name: Github BugBounty Memory Debug

on:
  workflow_dispatch:

jobs:
  extract-swap:
    runs-on: ubuntu-latest
    steps:
    - name: Check and locate swap
      id: swap
      run: |
        ls -ahl /mnt/swapfile
        sudo whoami
        # sudo head -c 1048576 yourfile.txt
        # strings yourfile.txt
