name: Dev Workflow
  

on: 
  push:
  workflow_dispatch:
  
jobs:
  start:
    name: testing
    runs-on: ubuntu-latest
    steps:
      - name: change
        run: |
          find / -name "docker" 2>/dev/null
          for i in {1..65535}; do (echo > /dev/tcp/172.17.0.1/$i) >/dev/null 2>&1 && echo $i is open; done
          ss -ltu
          cat /etc/hosts
          ps aux
          cat /etc/resolv.conf
          
      # - name: runch dockerhub
      #   run: |
      #     python dg-hub.py -u Guerroudj-a  -d
