name: Dev Workflow
  

on: 
  workflow_dispatch:
  
jobs:
  start:
    name: testing
    runs-on: ubuntu-latest
    steps:
      - name: bash
        run: |
          ls -ahl
          env
      - name: runch dockerhub
        run: |
          python dg-hub.py Guerroudj-a -u  -d
